### ISSUE TITLE
Some Hunting Horn Melodies have place-holders for their effects

### ISSUE THREAD

**Issue by richq** [gatheringhallstudios/MHGenDatabase#13]
The only missing feature I've spotted is in the Hunting Horn section, when showing some horns the Melodies tab shows Test A44 Test B44 or Test A50 Test B50 instead of the true effects.

This can be seen in the Lightning Flap for Att. & Def. Boost (S), or Giant's Koto 3+ for Hearing (S) + Wind Res.

**Comment by JosephMichels** [comment]
Thanks for submitting this. This has been fixed in the develop branch.
