### ISSUE TITLE
Database + icons licences

### ISSUE THREAD

**Issue by jeremyletang** [gatheringhallstudios/MHGenDatabase#26]
Hi Guys,

First thanks for the great work with this application, I really like it.
Unfortunately, I recently switch to an ios device, and there is no equivalent application on the store.
So I'm plan to write a similar app (at least for my own usage) for ios.

Here comes my question, I saw the MIT License at the root of the repository, but does it include the database and icon files ? (I would like to use them for my project, if it's possible).

How is updated the database ? Which resources do you use to create it ? And where the icons come from ?

Thanks.

**Comment by jaysondc** [comment]
Hey,

The MIT license includes the database and icons as they were generated by us, so they are free to use as long as you reach out.

The latest database file lives in the develop branch here:
https://github.com/gatheringhallstudios/MHGenDatabase/tree/develop/app/src/main/assets/databases

@JosephMichels created a tool that scrapes data directly from a game ROM and updates it whenever DLC comes out.

@kevinn creates item and monster icons for us.

I'm closing this but feel free to email me at jayson.p.delacruz@gmail.com
