### ISSUE TITLE
[Feature Request] Athena's ASS style armour set builder

### ISSUE THREAD

**Issue by Septolum** [gatheringhallstudios/MHGenDatabase#41]
Would it be possible to implement an armour set builder that works in a similar way to [Athena's Armour Set Search](https://m.facebook.com/AthenasArmorSetSearch/)?

**Comment by CarlosFdez** [comment]
This is an extraordinary late reply (sorry) but unfortunately we can't unless someone contributes it and/or decides to work with us on it.
