### ISSUE TITLE
Why not add Chinese translation?

### ISSUE THREAD

**Issue by binjie09** [gatheringhallstudios/MHGenDatabase#52]
Hi
In October, MHGU joined the official Chinese translation and joined many Chinese players. If it has Chinese translation, it will be welcomed by millions of Chinese monster hunter players.

**Comment by CarlosFdez** [comment]
Sorry for the late reply.

Something like this requires a merge program to add Chinese translations to all existing entries in the SQLite DB file, and a spreadsheet of translations for all existing fields.  Its not on the roadmap for anyone on our team but we're open to having volunteers implement it.

**Comment by ElChackAttack** [comment]
Is there anyone currently making any progress in regards to the translation? I would love to contribute towards it, anyone specifically I should contact?

**Comment by CarlosFdez** [comment]
Unfortunately, no one made any progression on this. Outside of major bugs the regular maintainers are no longer working on this project. 

You could contact me on the discord if you want real time correspondence on implementing such a feature though.

**Comment by CarlosFdez** [comment]
Closing as there has been no updates on this since January.
